
C:\Users\wangjing>conda.bat activate "C:\Users\wangjing\AppData\Local\Continuum\anaconda3\envs\pyhton27"

(pyhton27) C:\Users\wangjing>ls
'ls' is not recognized as an internal or external command,
operable program or batch file.

(pyhton27) C:\Users\wangjing>ls dir
'ls' is not recognized as an internal or external command,
operable program or batch file.

(pyhton27) C:\Users\wangjing>dir
 Volume in drive C has no label.
 Volume Serial Number is EEBC-F388

 Directory of C:\Users\wangjing

06/24/2020  08:05 AM    <DIR>          .
06/24/2020  08:05 AM    <DIR>          ..
02/07/2020  06:16 PM    <DIR>          .anaconda
06/24/2020  08:14 AM               699 .bash_history
06/30/2020  05:55 PM    <DIR>          .conda
06/30/2020  05:23 PM                43 .condarc
05/08/2020  12:46 PM    <DIR>          .config
06/23/2020  10:47 PM               163 .gitconfig
05/15/2020  01:37 PM    <DIR>          .ipynb_checkpoints
06/23/2020  09:31 AM    <DIR>          .ipython
05/15/2020  01:36 PM    <DIR>          .jupyter
06/30/2020  05:02 PM    <DIR>          .matplotlib
06/30/2020  04:41 PM    <DIR>          .pylint.d
06/30/2020  04:47 PM                25 .python_history
05/08/2020  12:46 PM    <DIR>          .spyder-py3
06/23/2020  10:54 PM    <DIR>          .ssh
04/21/2020  03:22 PM    <DIR>          .texlive2020
06/24/2020  08:08 AM    <DIR>          3D Objects
06/24/2020  08:08 AM    <DIR>          Contacts
03/03/2020  05:57 PM    <DIR>          Dropbox
06/23/2020  03:12 PM    <DIR>          EliesIch.github.io
06/24/2020  08:08 AM    <DIR>          Favorites
06/30/2020  05:54 PM    <DIR>          Homework
06/24/2020  08:08 AM    <DIR>          Links
02/10/2020  10:10 AM    <DIR>          ODBA
06/24/2020  08:09 AM    <DIR>          OneDrive
06/13/2020  03:22 AM    <DIR>          OneDrive - 岡山大学
02/01/2020  04:31 PM    <DIR>          Roaming
06/24/2020  08:08 AM    <DIR>          Saved Games
06/24/2020  08:08 AM    <DIR>          Searches
02/14/2020  04:17 PM    <DIR>          Wolfram Mathematica
               4 File(s)            930 bytes
              27 Dir(s)  306,569,732,096 bytes free

(pyhton27) C:\Users\wangjing>cd Homework

(pyhton27) C:\Users\wangjing\Homework>dir
 Volume in drive C has no label.
 Volume Serial Number is EEBC-F388

 Directory of C:\Users\wangjing\Homework

06/30/2020  05:54 PM    <DIR>          .
06/30/2020  05:54 PM    <DIR>          ..
06/26/2020  05:26 PM    <DIR>          .vscode
06/30/2020  05:52 PM             4,096 ._oscilloscope.py
05/12/2020  11:32 PM    <DIR>          Latex
06/26/2020  04:56 PM    <DIR>          Lecture note
05/12/2020  11:32 PM    <DIR>          New folder
12/16/2011  05:46 PM            17,016 oscilloscope.py
06/29/2020  06:35 PM             2,411 p1.png
08/26/2016  08:34 PM               729 PulseGetter.py
06/05/2020  06:03 PM    <DIR>          Python
06/23/2020  11:07 PM                42 README.md
06/15/2010  02:11 PM            14,317 td2csv.c
05/10/2020  04:34 PM    <DIR>          Tex
06/23/2020  11:43 PM                15 云端到本地测试1.0
               7 File(s)         38,626 bytes
               8 Dir(s)  306,569,732,096 bytes free

(pyhton27) C:\Users\wangjing\Homework>python
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 17:26:54) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import oscilloscope
>>> oscillo = oscilloscope.Oscilloscope("172.28.126.231")
>>> oscillo.getAcquireState().readline()
'0\n'
>>> oscillo.getAcquireState().readline()
'1\n'
>>> oscillo.getAcquireState().readline()
'1\n'
>>> oscillo.getAcquireState().readline()
'0\n'
>>> oscillo.setAcquireState("run")
>>> oscillo.setAcquireState("stop")
>>> exit()

(pyhton27) C:\Users\wangjing\Homework>python PulseGetter.py
Traceback (most recent call last):
  File "PulseGetter.py", line 24, in <module>
    if not os.path.exists( sys.argv[1]):
IndexError: list index out of range

(pyhton27) C:\Users\wangjing\Homework>python PulseGetter.py test 172.28.126.231 5 1
0
1
2
3
4

(pyhton27) C:\Users\wangjing\Homework>python PulseGetter.py test2 172.28.126.231 100 1
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

(pyhton27) C:\Users\wangjing\Homework>python PulseGetter.py singlephoton 172.28.126.231 1000 1
0
1
2
